export { pop }     from './src/pop.js'
export { push }    from './src/push.js'
export { shift }   from './src/shift.js'
export { unshift } from './src/unshift.js'
export { splices } from './src/splices.js'
