export { iterate, iterateXY, iterateY, indexedIterate, indexedMutate, } from './src/mapper'
export { side, head, getRow, getOr, getOrObj, getOrVec, }               from './src/indexes'
export { nestedToRows }                                                 from './src/convert'
export { transpose }                                                    from './src/algebra'
export { updateCell, appendCell, assignCell, updateCell as update, }    from './src/update'
export { indexedOf, indexedBy, indexedTo, indexed, }                    from './src/indexed'
