export { iterate, iterateXY, iterateY, indexedIterate, indexedMutate, } from './src/mapper.js'
export { side, head, getRow, getOr, getOrObj, getOrVec, }               from './src/indexes.js'
export { nestedToRows }                                                 from './src/convert.js'
export { transpose }                                                    from './src/algebra.js'
export { updateCell, appendCell, assignCell, updateCell as update, }    from './src/update.js'
export { indexedOf, indexedBy, indexedTo, indexed, }                    from './src/indexed.js'
