export { coins } from './src/coins'
export { isMatrix } from './src/isMatrix'
export { copyMargin } from './src/matrix-margin/copyMargin'
export { mapMargin } from './src/matrix-margin/mapMargin'
export { transpose } from '@vect/matrix-transpose'
export { mapper, mutate } from '@vect/matrix-mapper'
export { zipper, mutazip } from '@vect/matrix-zipper'
export { size, width } from '@vect/matrix-size'
