export { iterate }                                             from './src/iterate'
export { iterateKeys }                                         from './src/iterateKeys'
export { iterateEntries }                                      from './src/iterateEntries'
export { mapKeys, mapValues, mapEntries, mapValues as mapper } from './src/mapper'
export { mutate }                                              from './src/mutate'
