export { zipper }                                                           from './src/zipper'
export { mutazip }                                                          from './src/mutazip'
export { ColumnZipper }                                                     from './src/ColumnZipper'
export { ColumnMutazip }                                                    from './src/ColumnMutazip'
export { duozipper, trizipper, quazipper, Duozipper, Trizipper, Quazipper } from './src/seriesZipper'
export { iterzip }                                                          from './src/iterzip'
