export { iterate, iterateXY, iterateY, indexedIterate, indexedMutate, } from './src/mapper'
export { side, head }                                                   from './src/indexes'
export { nestedToRows }                                                 from './src/convert'
export { transpose }                                                    from './src/transpose'
export { indexed, simpleIndexed, filterIndexed, mappedIndexed }         from './src/generator'